/*
 * This file is generated by jOOQ.
*/
package com.dix.app.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Token implements Serializable {

    private static final long serialVersionUID = 194834618;

    private Long    id;
    private String  token;
    private Integer type;
    private Integer status;
    private Long    userId;
    private Integer expireTime;
    private Long    createTime;
    private Long    updateTime;

    public Token() {}

    public Token(Token value) {
        this.id = value.id;
        this.token = value.token;
        this.type = value.type;
        this.status = value.status;
        this.userId = value.userId;
        this.expireTime = value.expireTime;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Token(
        Long    id,
        String  token,
        Integer type,
        Integer status,
        Long    userId,
        Integer expireTime,
        Long    createTime,
        Long    updateTime
    ) {
        this.id = id;
        this.token = token;
        this.type = type;
        this.status = status;
        this.userId = userId;
        this.expireTime = expireTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getExpireTime() {
        return this.expireTime;
    }

    public void setExpireTime(Integer expireTime) {
        this.expireTime = expireTime;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Token (");

        sb.append(id);
        sb.append(", ").append(token);
        sb.append(", ").append(type);
        sb.append(", ").append(status);
        sb.append(", ").append(userId);
        sb.append(", ").append(expireTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
