/*
 * This file is generated by jOOQ.
*/
package com.dix.app.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBind implements Serializable {

    private static final long serialVersionUID = -158177390;

    private Long    id;
    private Long    userId;
    private Integer type;
    private String  outerUserId;
    private String  data;
    private Long    createTime;
    private Long    updateTime;
    private Integer weight;

    public UserBind() {}

    public UserBind(UserBind value) {
        this.id = value.id;
        this.userId = value.userId;
        this.type = value.type;
        this.outerUserId = value.outerUserId;
        this.data = value.data;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.weight = value.weight;
    }

    public UserBind(
        Long    id,
        Long    userId,
        Integer type,
        String  outerUserId,
        String  data,
        Long    createTime,
        Long    updateTime,
        Integer weight
    ) {
        this.id = id;
        this.userId = userId;
        this.type = type;
        this.outerUserId = outerUserId;
        this.data = data;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.weight = weight;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getOuterUserId() {
        return this.outerUserId;
    }

    public void setOuterUserId(String outerUserId) {
        this.outerUserId = outerUserId;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getWeight() {
        return this.weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserBind (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(type);
        sb.append(", ").append(outerUserId);
        sb.append(", ").append(data);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(weight);

        sb.append(")");
        return sb.toString();
    }
}
