/*
 * This file is generated by jOOQ.
*/
package com.dix.app.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 8502438;

    private Long    id;
    private String  uid;
    private String  username;
    private String  phone;
    private String  password;
    private String  email;
    private String  name;
    private String  tel;
    private Integer gender;
    private String  avatar;
    private Integer sourceId;
    private Integer sourceType;
    private Integer sourceClient;
    private Integer weight;
    private Long    createTime;
    private Long    updateTime;
    private Integer birthday;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.uid = value.uid;
        this.username = value.username;
        this.phone = value.phone;
        this.password = value.password;
        this.email = value.email;
        this.name = value.name;
        this.tel = value.tel;
        this.gender = value.gender;
        this.avatar = value.avatar;
        this.sourceId = value.sourceId;
        this.sourceType = value.sourceType;
        this.sourceClient = value.sourceClient;
        this.weight = value.weight;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.birthday = value.birthday;
    }

    public User(
        Long    id,
        String  uid,
        String  username,
        String  phone,
        String  password,
        String  email,
        String  name,
        String  tel,
        Integer gender,
        String  avatar,
        Integer sourceId,
        Integer sourceType,
        Integer sourceClient,
        Integer weight,
        Long    createTime,
        Long    updateTime,
        Integer birthday
    ) {
        this.id = id;
        this.uid = uid;
        this.username = username;
        this.phone = phone;
        this.password = password;
        this.email = email;
        this.name = name;
        this.tel = tel;
        this.gender = gender;
        this.avatar = avatar;
        this.sourceId = sourceId;
        this.sourceType = sourceType;
        this.sourceClient = sourceClient;
        this.weight = weight;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.birthday = birthday;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    public Integer getSourceType() {
        return this.sourceType;
    }

    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    public Integer getSourceClient() {
        return this.sourceClient;
    }

    public void setSourceClient(Integer sourceClient) {
        this.sourceClient = sourceClient;
    }

    public Integer getWeight() {
        return this.weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(uid);
        sb.append(", ").append(username);
        sb.append(", ").append(phone);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(name);
        sb.append(", ").append(tel);
        sb.append(", ").append(gender);
        sb.append(", ").append(avatar);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(sourceType);
        sb.append(", ").append(sourceClient);
        sb.append(", ").append(weight);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(birthday);

        sb.append(")");
        return sb.toString();
    }
}
