/*
 * This file is generated by jOOQ.
*/
package com.dix.app.jooq.tables;


import com.dix.app.jooq.Dix;
import com.dix.app.jooq.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBind extends TableImpl<Record> {

    private static final long serialVersionUID = -713768591;

    /**
     * The reference instance of <code>dix.user_bind</code>
     */
    public static final UserBind USER_BIND = new UserBind();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>dix.user_bind.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>dix.user_bind.user_id</code>.
     */
    public final TableField<Record, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dix.user_bind.type</code>.
     */
    public final TableField<Record, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dix.user_bind.outer_user_id</code>.
     */
    public final TableField<Record, String> OUTER_USER_ID = createField("outer_user_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dix.user_bind.data</code>.
     */
    public final TableField<Record, String> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>dix.user_bind.create_time</code>.
     */
    public final TableField<Record, Long> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dix.user_bind.update_time</code>.
     */
    public final TableField<Record, Long> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>dix.user_bind.weight</code>.
     */
    public final TableField<Record, Integer> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>dix.user_bind</code> table reference
     */
    public UserBind() {
        this("user_bind", null);
    }

    /**
     * Create an aliased <code>dix.user_bind</code> table reference
     */
    public UserBind(String alias) {
        this(alias, USER_BIND);
    }

    private UserBind(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private UserBind(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dix.DIX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_USER_BIND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_USER_BIND_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.KEY_USER_BIND_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserBind as(String alias) {
        return new UserBind(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserBind rename(String name) {
        return new UserBind(name, null);
    }
}
