/*
 * This file is generated by jOOQ.
*/
package com.dix.app.jooq;


import com.dix.app.jooq.tables.Token;
import com.dix.app.jooq.tables.User;
import com.dix.app.jooq.tables.UserBind;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dix extends SchemaImpl {

    private static final long serialVersionUID = 1982160452;

    /**
     * The reference instance of <code>dix</code>
     */
    public static final Dix DIX = new Dix();

    /**
     * The table <code>dix.token</code>.
     */
    public final Token TOKEN = com.dix.app.jooq.tables.Token.TOKEN;

    /**
     * The table <code>dix.user</code>.
     */
    public final User USER = com.dix.app.jooq.tables.User.USER;

    /**
     * The table <code>dix.user_bind</code>.
     */
    public final UserBind USER_BIND = com.dix.app.jooq.tables.UserBind.USER_BIND;

    /**
     * No further instances allowed
     */
    private Dix() {
        super("dix", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Token.TOKEN,
            User.USER,
            UserBind.USER_BIND);
    }
}
