/*
 * This file is generated by jOOQ.
*/
package com.dix.app.jooq;


import com.dix.app.jooq.tables.Token;
import com.dix.app.jooq.tables.User;
import com.dix.app.jooq.tables.UserBind;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>dix</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Long> IDENTITY_TOKEN = Identities0.IDENTITY_TOKEN;
    public static final Identity<Record, Long> IDENTITY_USER = Identities0.IDENTITY_USER;
    public static final Identity<Record, Long> IDENTITY_USER_BIND = Identities0.IDENTITY_USER_BIND;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> KEY_TOKEN_PRIMARY = UniqueKeys0.KEY_TOKEN_PRIMARY;
    public static final UniqueKey<Record> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<Record> KEY_USER_BIND_PRIMARY = UniqueKeys0.KEY_USER_BIND_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<Record, Long> IDENTITY_TOKEN = createIdentity(Token.TOKEN, Token.TOKEN.ID);
        public static Identity<Record, Long> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
        public static Identity<Record, Long> IDENTITY_USER_BIND = createIdentity(UserBind.USER_BIND, UserBind.USER_BIND.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<Record> KEY_TOKEN_PRIMARY = createUniqueKey(Token.TOKEN, "KEY_token_PRIMARY", Token.TOKEN.ID);
        public static final UniqueKey<Record> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
        public static final UniqueKey<Record> KEY_USER_BIND_PRIMARY = createUniqueKey(UserBind.USER_BIND, "KEY_user_bind_PRIMARY", UserBind.USER_BIND.ID);
    }
}
