/*
 * This file is generated by jOOQ.
*/
package com.dix.app.jooq;


import com.dix.app.jooq.tables.Token;
import com.dix.app.jooq.tables.User;
import com.dix.app.jooq.tables.UserBind;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dix
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dix.token</code>.
     */
    public static final Token TOKEN = com.dix.app.jooq.tables.Token.TOKEN;

    /**
     * The table <code>dix.user</code>.
     */
    public static final User USER = com.dix.app.jooq.tables.User.USER;

    /**
     * The table <code>dix.user_bind</code>.
     */
    public static final UserBind USER_BIND = com.dix.app.jooq.tables.UserBind.USER_BIND;
}
